# Generated by Django 5.0.6 on 2024-06-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_course_registration_app', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='languages_used',
            field=models.CharField(default='', max_length=100),
        ),
    ]
