# Generated by Django 5.0.6 on 2024-06-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_course_registration_app', '0003_project_languages_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='projects',
            field=models.CharField(default='', max_length=100),
        ),
    ]
