# Generated by Django 5.0.6 on 2024-06-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_course_registration_app', '0004_student_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='projects',
        ),
        migrations.AddField(
            model_name='student',
            name='projects',
            field=models.ManyToManyField(blank=True, to='student_course_registration_app.project'),
        ),
    ]
