# Generated by Django 5.0.6 on 2024-06-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_course_registration_app', '0005_remove_student_projects_student_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.CharField(default='', max_length=100),
        ),
    ]
